services:
  postgres-dev:
    image: postgres:16
    container_name: toxic-bet-dev
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEV_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DEV_USER} -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-docker:
    image: postgres:16
    container_name: toxic-bet
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_DOCKER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DOCKER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DOCKER_DB}
    ports:
      - "5440:5432"
    volumes:
      - postgres_docker_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DOCKER_USER} -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_dev_data:
  postgres_docker_data:
