spring:
  application:
    name: toxic-bet

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DEV_HOST:localhost}:${POSTGRES_DEV_PORT:5435}/${POSTGRES_DEV_DB}
    username: ${POSTGRES_DEV_USER}
    password: ${POSTGRES_DEV_PASSWORD}

  flyway:
    url: jdbc:postgresql://${POSTGRES_DEV_HOST:localhost}:${POSTGRES_DEV_PORT:5435}/${POSTGRES_DEV_DB}
    user: ${POSTGRES_DEV_USER}
    password: ${POSTGRES_DEV_PASSWORD}
    enabled: true

  sql:
    init:
      mode: always

server:
  port: 10000